import Head from 'next/head';
import { Box, Button, Container, Grid } from '@material-ui/core';
import { ProviderRow } from '../components/ProviderRow';
import { AddButton } from '../components/AddButton';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pi-mon</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container>
          <Grid container spacing={3}>
            <Grid item xs={12}>
              <h1>Pi-mon</h1>
            </Grid>
            <Grid item xs={12}>
              <Box display='flex' justifyContent='flex-end'>
                <AddButton />
              </Box>
            </Grid>
            <Grid item xs={12}>
              <ProviderRow name='Test' params={{ test: 'test' }} />
            </Grid>
          </Grid>
        </Container>
      </main>
    </div>
  );
}
