import Head from 'next/head';
import { Box, Container, Grid } from '@material-ui/core';
import { createTheme, ThemeProvider } from '@material-ui/core/styles';
import CssBaseline from '@material-ui/core/CssBaseline';
import useMediaQuery from '@material-ui/core/useMediaQuery';
import { ProviderRow } from '../components/ProviderRow';
import { EditButton } from '../components/EditButton';
import { useMemo } from 'react';
import { ServiceProvidersList } from './serviceProviders/views/List';

export default function Home() {
  const prefersDarkMode = useMediaQuery('(prefers-color-scheme: dark)');

  const theme = useMemo(
    () =>
      createTheme({
        palette: {
          type: prefersDarkMode ? 'dark' : 'light',
        },
      }),
    [prefersDarkMode],
  );
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Head>
        <title>Pi-mon</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container>
          <Box>
            <h1>Pi-mon</h1>
          </Box>
          <Box display='flex' justifyContent='flex-end' paddingBottom='20px'>
            <EditButton label='Add' />
          </Box>
          <ServiceProvidersList />
        </Container>
      </main>
    </ThemeProvider>
  );
}
