import Head from 'next/head';
import { Box, Container, Grid } from '@material-ui/core';
import { createTheme, ThemeProvider } from '@material-ui/core/styles';
import CssBaseline from '@material-ui/core/CssBaseline';
import useMediaQuery from '@material-ui/core/useMediaQuery';
import { ProviderRow } from '../components/ProviderRow';
import { AddButton } from '../components/AddButton';
import { useMemo } from 'react';

export default function Home() {
  const prefersDarkMode = useMediaQuery('(prefers-color-scheme: dark)');

  const theme = useMemo(
    () =>
      createTheme({
        palette: {
          type: prefersDarkMode ? 'dark' : 'light',
        },
      }),
    [prefersDarkMode],
  );
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Head>
        <title>Pi-mon</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container>
          <Grid container spacing={3}>
            <Grid item xs={12}>
              <h1>Pi-mon</h1>
            </Grid>
            <Grid item xs={12}>
              <Box display='flex' justifyContent='flex-end'>
                <AddButton />
              </Box>
            </Grid>
            <Grid item xs={12}>
              <ProviderRow name='Test' params={{ test: 'test' }} />
            </Grid>
          </Grid>
        </Container>
      </main>
    </ThemeProvider>
  );
}
